version: '3.3'
services:
  nginx:
    image: nginx:stable
    ports:
      - 8989:80
    depends_on:
      - php
    volumes:
      - .:/[project]
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  php:
    build: ./docker/php/
    volumes:
      - .:/[project]
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
      #- redis
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASS=root
      - DB_NAME=
  
  db:
    image: mysql:8.0.29-oracle
    ports:
      - 3366:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
      
      #redis:
      #image: redis:5.0.6-alpine
      #ports:
      #- "6382:6379"
      
      #adminer:
      #image: adminer:4.2.5-standalone
      #ports:
      #- 8080:8080

volumes:
  db_data: